### ISSUE TITLE
Consider a placeholder for invalid JSON

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab_json#20]
Right now, invalid JSON results in empty output and an console log.  Perhaps catch [this](https://github.com/jupyterlab/jupyterlab_json/blob/11a3b6ee99279b51550d1f60b8f35d9b1a97c5b4/labextension/src/doc.js#L46) and render an error message?

![image](https://cloud.githubusercontent.com/assets/2096628/23214758/7d0a5896-f8d5-11e6-9a49-45a798f333d1.png)

**Comment by gnestor** [comment]
@blink1073 I'm trying to test and I'm currently seeing this behavior when trying to open a JSON file using jupyterlab_json:

![screencap](http://g.recordit.co/pVZ2BF9Lbb.gif)

3 things to observe:

* The "Open With" doesn't expand on hover, only on click
* The tab title is blank
* When I close the tab, it looks like:

![image](https://cloud.githubusercontent.com/assets/512354/23320462/bd4c15fa-fa8f-11e6-8e59-48142a010685.png)

The error:

```
Uncaught (in promise) Error: Widget is not contained in the dock panel.
    at DockPanel.activateWidget (main.bundle.js:15135)
    at ApplicationShell.activateMain (main.bundle.js:22365)
    at Object.open (main.bundle.js:103370)
    at DocumentManager._createOrOpenDocument (main.bundle.js:103751)
    at DocumentManager.openOrReveal (main.bundle.js:103523)
    at FileButtons.open (main.bundle.js:99279)
    at CommandRegistry.execute (main.bundle.js:2317)
    at Menu.triggerActiveItem (main.bundle.js:18581)
    at Menu._evtMouseUp (main.bundle.js:18917)
    at Menu.handleEvent (main.bundle.js:18727)
```

Did any APIs related to DocRegistry change recently?

**Comment by blink1073** [comment]
The first looks like a bug in JLab.  The second two are because you need to switch to `@phosphor/widgets` for compatibility.

**Comment by gnestor** [comment]
Right you are! I'll create an issue for the first one and update the extensions...

**Comment by gnestor** [comment]
@blink1073 Here's what I have so far:

<img width="1280" alt="screen shot 2017-02-28 at 12 29 11 pm" src="https://cloud.githubusercontent.com/assets/512354/23436857/d991a28c-fdc0-11e6-9354-06fd7d8f6e2c.png">

Good suggestion, BTW! I'm going to add this to mimerender-cookiecutter because it's relevant to all document rendering. 

I'd like to offer syntax highlighting for the JSON snippet and I managed to track down [this line](https://github.com/jupyterlab/jupyterlab/blob/4564240df87748225dc4149bed3974bc43363adb/src/renderers/widget.ts#L118-L119) that appears to use CodeMirror to highlight code blocks in Markdown. I'd like to import jupyterlab's CodeMirror as a plugin (like we discussed [here](https://github.com/jupyterlab/jupyterlab/issues/1339#issuecomment-281426998)), which currently isn't possible. 

Does jupyterlab currently provide anything that can do syntax highlighting? If not, do you think using CodeMirror via jupyterlab is a good solution?

**Comment by blink1073** [comment]
We could provide syntax highlighting as a service, which would by default be provided by CodeMirror.  The highlighter would have to be passed to the renderers as part of the render options.   Feel free to open an issue for this.

**Comment by gnestor** [comment]
I was thinking that the highlight service could be provided somewhere in the codemirror namespace (e.g. `codemirror/highlight`), but whatever's clever.

**Comment by gnestor** [comment]
Closed by https://github.com/jupyterlab/jupyterlab_json/pull/22
